require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-graphql
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile.lock'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'app/helpers/**/*'
    - 'config/environments/**/*'
    - 'app/jobs/**/*'
    - 'tmp/**/*'
  NewCops: enable

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/FieldMethod:
  Enabled: false

# This is currently exiting with a rubocop exception error and should be
# resolved hopefully a future update
# "An error occurred while Rails/UniqueValidationWithoutIndex cop was inspecting"
# To see the complete backtrace run rubocop -d.
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'app/adapters/highchart/finances_charts_adapter.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/models/flow/contracts_flow_information.rb'
    - 'app/controllers/graphql_controller.rb'
    - 'app/controllers/concerns/**/*'
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'lib/tasks/consolidate_flows.rake'

Metrics/ClassLength:
  Exclude:
    - 'app/adapters/highchart/finances_charts_adapter.rb'
    - 'app/data_objects/replenishing_data.rb'
    - 'app/repositories/demands_repository.rb'
    - 'app/models/company.rb'
    - 'app/models/project.rb'
    - 'app/models/team.rb'
    - 'app/models/consolidations/project_consolidation.rb'
    - 'app/models/demand.rb'
    - 'app/models/membership.rb'
    - 'app/models/flow/work_item_flow_information.rb'
    - 'app/models/flow/contracts_flow_information.rb'
    - 'app/models/demand_transition.rb'
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/demands_controller.rb'
    - 'app/controllers/companies_controller.rb'
    - 'app/controllers/teams_controller.rb'
    - 'app/controllers/team_members_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/controllers/demand_blocks_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/services/stats/statistics_service.rb'
    - 'app/services/demand_effort_service.rb'
    - 'app/graphql/types/**/*'
    - 'app/adapters/**/*'
    - 'app/readers/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'
    - 'app/controllers/demands_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/adapters/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'app/controllers/home_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/data_objects/replenishing_data.rb'
  Max: 21

Metrics/ParameterLists:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/Presence:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
