require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile.lock'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'app/helpers/**/*'
    - 'config/environments/**/*'
    - 'app/jobs/**/*'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Metrics/MethodLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'app/adapters/highchart/finances_charts_adapter.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/models/flow/contracts_flow_information.rb'
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Metrics/ClassLength:
  Exclude:
    - 'app/adapters/highchart/operational_charts_adapter.rb'
    - 'app/adapters/highchart/status_report_charts_adapter.rb'
    - 'app/adapters/highchart/finances_charts_adapter.rb'
    - 'app/data_objects/replenishing_data.rb'
    - 'app/repositories/demands_repository.rb'
    - 'app/models/company.rb'
    - 'app/models/project.rb'
    - 'app/models/project_consolidation.rb'
    - 'app/models/demand.rb'
    - 'app/models/flow/work_item_flow_informations.rb'
    - 'app/models/flow/contracts_flow_information.rb'
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/demands_controller.rb'
    - 'app/controllers/companies_controller.rb'
    - 'app/controllers/teams_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/adapters/**/*'
    - 'app/readers/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'
    - 'app/controllers/demands_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/adapters/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'app/controllers/home_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'
    - 'app/data_objects/replenishing_data.rb'
  Max: 21

Metrics/ParameterLists:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false
