AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'app/helpers/**/*'
    - 'lib/tasks/seed.rake'
    - 'lib/tasks/migrate_current_projects_to_jira.rake'
    - 'config/environments/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Metrics/ClassLength:
  Exclude:
    - 'app/models/project.rb'
    - 'app/repositories/project_results_repository.rb'
    - 'app/adapters/pipefy/pipefy_card_adapter.rb'
    - 'app/adapters/highchart/operational_charts_adapter.rb'
    - 'app/adapters/highchart/status_report_charts_adapter.rb'
    - 'app/models/demand.rb'
    - 'app/controllers/projects_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
  Max: 18.5

Metrics/ParameterLists:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false
