require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile.lock'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'app/helpers/**/*'
    - 'config/environments/**/*'
    - 'app/jobs/**/*'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'app/adapters/highchart/finances_charts_adapter.rb'
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Metrics/ClassLength:
  Exclude:
    - 'app/adapters/highchart/operational_charts_adapter.rb'
    - 'app/adapters/highchart/status_report_charts_adapter.rb'
    - 'app/adapters/highchart/finances_charts_adapter.rb'
    - 'app/data_objects/replenishing_data.rb'
    - 'app/repositories/demands_repository.rb'
    - 'app/models/company.rb'
    - 'app/models/project.rb'
    - 'app/models/project_consolidation.rb'
    - 'app/models/demand.rb'
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/demands_controller.rb'
    - 'app/controllers/companies_controller.rb'
    - 'app/adapters/**/*'
    - 'app/readers/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'
    - 'app/controllers/demands_controller.rb'
    - 'app/adapters/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/base_report_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/routes/**/*'
    - 'db/migrate/**/*'
    - 'app/controllers/home_controller.rb'
    - 'app/services/slack/slack_notification_service.rb'
  Max: 18.5

Metrics/ParameterLists:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false
