version: 2.1
orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

jobs:
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:12.4
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: "postgres"
          POSTGRES_DB: flowcontrol_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: "postgres"
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - run: gem update --system
      - run: bundle install --jobs=4 --retry=3
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/.bundle
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
      - run: bundle exec rubocop

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test