version: 2.1
orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

jobs:
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:12.4
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: "postgres"
          POSTGRES_DB: flowcontrol_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: "postgres"
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - run: sudo apt-get update
      - run: sudo apt install postgresql-client
      - checkout
      - run: bundle install --jobs=4 --retry=3
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: rake db:create
      - run: bundle exec rake db:structure:load
      - run: bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
      - run: bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - test