version: 2
jobs:
  build:
    working_directory: ~/flowclimate
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          PGHOST: localhost
          PGUSER: "postgres"
          RAILS_ENV: test
      - image: postgres:12.4
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: flowcontrol_test
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install nodejs
      - run: sudo apt install postgresql-client
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: flowclimate-{{ checksum "Gemfile.lock" }}

#      - run: gem update --system
#      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - run: bundle install

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: flowclimate-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec