version: 2
jobs:
  build:
    working_directory: ~/flowclimate
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          PGHOST: localhost
          PGUSER: "postgres"
          RAILS_ENV: test
      - image: postgres:12.4
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: flowcontrol_test
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install nodejs
      - run: sudo apt install postgresql-client
      - checkout

      - run: bundle install

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rails db:structure:load

      # Run the tests
      - run:
        name: Tests
        command: |
          TESTFILES=$(circleci tests glob "spec/**/*.rb" | circleci tests split --split-by=timings)
          bundle exec rspec -- ${TESTFILES}