default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: flowcontrol_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: flowcontrol_test<%= Figaro.env.test_env_number %>
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: flowcontrol_production
  username: flowcontrol
  password: <%= Figaro.env.flowcontrol_database_password %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
