default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: flowcontrol_development
  host: localhost
  username:
  password:

test:
  <<: *default
  database: flowcontrol_test
  host: localhost
  username:
  password:

production:
  <<: *default
  database: flowcontrol_production
  username: flowcontrol
  password: <%= Figaro.env.flowcontrol_database_password %>
