staging:
  :concurrency: 1
development:
  :concurrency: <%= ENV['SIDEKIQ_THREADS'] || 5 %>
production:
  :concurrency: <%= ENV['SIDEKIQ_THREADS'] || 14 %>
queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]

limits:
  default: 8
  low: 6