staging:
  :concurrency: 1
development:
  :concurrency: 5
production:
  :concurrency: 3
queues:
  - ['default', 1]
  - ['generators', 1]
  - ['project_update', 1]
  - ['demand_update', 1]
  - ['consolidations', 1]
  - ['dashboards', 1]
limits:
  consolidations: 2
  dashboards: 2
