staging:
  :concurrency: 1
development:
  :concurrency: <%= ENV['SIDEKIQ_THREADS'] || 5 %>
production:
  :concurrency: <%= ENV['SIDEKIQ_THREADS'] || 5 %>
queues:
  - critical
  - default
  - low

limits:
  default: 5
  low: 10