staging:
  :concurrency: 1
development:
  :concurrency: <%= ENV['SIDEKIQ_THREADS'] || 5 %>
production:
  :concurrency: <%= ENV['SIDEKIQ_THREADS'] || 2 %>
queues:
  - ['default', 1]
  - ['critical', 1]
  - ['low', 1]
