staging:
  :concurrency: 1
development:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - ['default', 1]
  - ['generators', 1]
  - ['project_update', 1]
  - ['demand_update', 1]
  - ['consolidations', 1]
