export type ProjectConsolidation = {
  leadTimeMin: number
  leadTimeMax: number
  leadTimeFeature: number
  leadTimeBug: number
  leadTimeChore: number
  leadTimeStandard: number
  leadTimeFixedDate: number
  leadTimeExpedite: number
  leadTimeStdDev: number
  leadTimeAverage: number
  demandsFinishedIds: number[]
  leadTimeHistogramBinMin: number
  leadTimeHistogramBinMax: number
  leadTimeRangeMonth: number
  leadTimeMinMonth: number
  leadTimeMaxMonth: number
  histogramRange: number
  interquartileRange: number
  leadTimeP25: number
  leadTimeP75: number
  leadTimeP65: number
  leadTimeP80: number
  leadTimeP95: number
  projectQuality: number
  consolidationDate: string
  operationalRisk: number
  tasksBasedOperationalRisk: number
  codeNeededBlocksCount: number
  codeNeededBlocksPerDemand: number
  flowEfficiency: number
  hoursPerDemand: number
  projectThroughput: number
  projectThroughputHours: number
  bugsOpened: number
  bugsClosed: number
  projectThroughputHoursInMonth: number
  projectThroughputHoursManagementInMonth: number
  projectThroughputHoursDevelopmentInMonth: number
  projectThroughputHoursDesignInMonth: number
  projectThroughputHoursManagement: number
  projectThroughputHoursDevelopment: number
  projectThroughputHoursDesign: number
  projectThroughputHoursUpstream: number
  projectThroughputHoursDownstream: number
  projectThroughputHoursAdditional?: number
  projectTasksThroughput: number
}
