name: FlowClimateBuild
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run linters
        run: |
          bundle exec rubocop --parallel

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: flowcontrol_test
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: test
          PG_HOST: localhost
          PG_USER: ""
          PG_PASSWORD: ""
          PG_PORT: ${{ job.services.postgres.ports['5432'] }}
        run: |
          bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec
        env:
          secret_key_32_encoded: "8L+WeHTWhNtEAvQzoRaYqYtl4VCwDMReh2SzicO/iCA=\n"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: "pNBUygMPs3g/KG5wZvMFWRObDR1b01NTmdHMrpvfJQZQWkYh9EwRkdY2HqWOTazgJISHKDcKx0besZyb0BkqzMUQruCfzKM9fxrpPxeYbdIMadDOuRur2ZZ8RzqjHJ+F3p9mnC8o27zqe4QcU4H+vnQAXWXI6OBt6rYzAEXFyq3H05Qjn6gDiUxFZOvL7zZJRDyBLYIONu7yOiP1NOaii/lggHaCN4WfhFNC7V0NMCp7A9o+yWfmUZDUbxNvTVbN6z1X42PCkYQ6LUWWC7QFKOFZfs6HO9Vn9YIH/0ezE/KhpUf59rzhZuhJ46aWwLUIZ5w9pDjCeJ7xnakAA4YsQ7z/LIiuRJCprwb1W6RLUIQ9Tzkfx9n+wN1J0s39cfPubuMz6N+7pAS78R7Xde7kCR+jzDU1R73K6CtduycRnRIpBO310WVxaxROIiX8F+zx88b8oCIJfOrgMSFrYG5WNs/xW1sKoOsMUp3ILH5hUg7Fue1BelLvnnle8M2sXjN/FKSw8B/vJXeYz40l/o+LhdALqQfeR5oFr1Dq2IZBYCuoHmmXgoRNhbLH7VxUKB3KfUN87GufQnGNVTpsbQwwbhDN+45al0CZXQXxN9Vn1tq8zwSIeFVzu6HNYwOh+vIK6aeyh+iu90a/hL7TCO58EwWalMhNZluf3Zm3vqm0QbU="
          heroku_app_name: "flowclimatestaging" #Must be unique in Heroku
